version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    networks: 
      - camagru
    environment: 
      - NGINX_PORT=80
    volumes:
      - ./conf/nginx:/etc/nginx
      - ./camagru:/var/www/nginx/camagru
    depends_on: 
      - php
      - mysql

  php:
    container_name: php
    expose:
      - 9000
    networks:
      - camagru
    volumes:
      - ./camagru:/var/www/html
      - ./conf/php/etc:/usr/local/etc
      - ./conf/php/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
      - ./conf/php/ssmtp/php-mail.conf:/usr/local/etc/php/conf.d/mail.ini:ro
    build:
      context: .
      dockerfile: Dockerfile-php
    depends_on:
      - mysql

  # With the latest version of mysql, ALTER USER 'root' IDENTIFIED WITH mysql_native_passwordBY 'password';
  # To enable connection from mysql.
  mysql:
    image: mysql
    container_name: mysql
    networks:
      - camagru
    volumes:
      - mysql_db:/var/lib/mysql
      - ./conf/mysql:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=camagru
    expose:
      - 3306
volumes:
  mysql_db:
networks:
  camagru:
