FROM php:fpm

RUN apt-get update && apt-get install -y zip unzip libpq-dev libpng-dev libjpeg-dev libfreetype6-dev  libjpeg62-turbo-dev libgd-dev

# Install sSMTP for mail support
RUN apt-get install -y -q --no-install-recommends \
		ssmtp \
	&& apt-get clean \
	&& rm -r /var/lib/apt/lists/*


RUN docker-php-ext-install pdo \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install pdo_pgsql 

    # && docker-php-ext-install pdo_mysqli

RUN  docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd


 # RUN docker-php-ext-configure bcmath --enable-bcmath \
 #    && docker-php-ext-configure intl --enable-intl \
 #    && docker-php-ext-configure pcntl --enable-pcntl \
 #    && docker-php-ext-configure mysqli --with-mysqli \
 #    && docker-php-ext-configure pdo_mysql --with-pdo-mysql \
 #    && docker-php-ext-configure pdo_pgsql --with-pgsql \
 #    && docker-php-ext-install pdo bcmath intl pcntl mysqli pdo pdo_mysql pdo_pgsql

# RUN ln- s /usr/src/php/ext/pdo_mysql /usr/local/lib/php/extensions/no-debug-non-zts-20180731